### PR TITLE
[IIIF-248] set up dockerhub deploy logic in Travis config

### PR DESCRIPTION
**Pull request by hardyoyo**
- works in concert with another change in the manifest-store application repository, which will trigger a build on this repository and include a MANIFESTSTORE_TAG environment variable
- requires DockerHub credentials to be added to the Travis-CI configuration on the travis-ci.com site as environment variables

### CODE REVIEW

**Comment by hardyoyo** [comment]
**Ready for merge**, confirmed working by setting all environment variables, including MANIFESTSTORE_TAG, in the Travis-CI settings tab for this repository. MANIFESTSTORE_TAG has since been removed from the Travis-CI settings tab.

**Comment by cachemeoutside** [comment]
In your tests prior to merging the PR, did you confirm if the trigger pushed a container image to dockerhub? I don't see a tagged version here:

https://cloud.docker.com/u/uclalibrary/repository/docker/uclalibrary/manifest-store

Presuming you might've delete it afterwards though.

**Comment by hardyoyo** [comment]
@cachemeoutside you mean this one? https://cloud.docker.com/u/uclalibrary/repository/docker/uclalibrary/manifest-store/tags

**Comment by ksclarke** [comment]
I believe @cachemeoutside meant a tagged one other than 'latest' since we'll have real tagged ones in addition to latest, but for the purposes of this build a tag is a tag since it's just something that's passed in via the travis trigger on the other repo.

Did you create a ticket for re-pinning git with the correct version?

**Comment by hardyoyo** [comment]
thanks for the reminder: https://jira.library.ucla.edu/browse/IIIF-333

**Pull request merged**
